version: "2"
run:
  go: "1.24"
  modules-download-mode: mod
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - zerologlint
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - printf
        - fieldalignment
        - shadow
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1020
  exclusions:
    generated: lax
    paths:
      - swagger-ui
      - configs
      - templates
      - \.go
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com)
        - localmodule
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - swagger-ui
      - configs
      - templates
      - \.go
      - third_party$
      - builtin$
      - examples$
