serverPort: ":8080"

database:
  dbUserEnv: "DB_USER"
  dbPasswordEnv: "DB_PASSWORD"
  dbNameEnv: "DB_NAME"
  dbHostEnv: "DB_HOST"
  dbPortEnv: "DB_PORT"

jwt:
  secretEnv: "JWT_SECRET"
  accessTokenDuration: 3600      # 1 hour in seconds
  refreshTokenDuration: 604800   # 7 days in seconds